### ISSUE TITLE
Deploy Minio instance at Jena.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#130]
**Description of the feature** 
Deploy an instance of Minio at Jena @https://minio.nmrxiv.org

**Implementation steps or Task**
- [x] VM Provisioning 
- [x] Cluster creation in Rancher
- [x] Expand the storage to 16TB provided by the URZ.(Right now its 70GB)
- [x] Deploy Minio via Helm Chart.
- [x] Hook up the storage file system
- [x] Expose the API or URL
- [x] Integration testing with Laravel

**Comment by NishaSharma14** [comment]
As discussed with URZ the plan is to move to Ceph Storage at some point when its ready.
