### ISSUE TITLE
Data Contingency Plan for Minio and Database.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#131]
**Description of the feature** 
Implement a data backup or contingency plan for the Minio instance and Database.

**Implementation steps or Task**
- [ ] Connect with URZ and understand how the data backup for extended disk works as of now
- [ ] Prepare a CRON job to take back
- [ ] Scheduler to export db
- [ ] Upload the db exports to dedicated storage on the minio buckets

***Tips*** You can split your feature into different small tasks and convert each task to a sub-feature or sub-task. This sample feature can be taken as a reference - https://github.com/NFDI4Chem/nmrxiv/issues/65
