### ISSUE TITLE
Provide ISA configuration of NMR assay for a "pure" compound

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#160]
**Description of the feature** 
Provide the configuration with python tools including the protocols and the parameters.

**Implementation steps or Task**
- [ ] Contact ISA team and get the up to date tools for creating configurations
- [ ] Design the configuration
- [ ] Present the design and receive comments
- [ ] Create the configuration
- [ ] Present the configuration 
- [ ] Final fixing
- [ ] Publish to ISA configurations
- [ ] Implement in nmrXiv
