### ISSUE TITLE
Update documentation (v1.0.0).

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#434]
**Describe the issue**
Update the documentation for v1.0.0 release.

- [ ] [Implement versioning and redeploy](https://github.com/NFDI4Chem/nmrxiv/issues/415). **Nisha**
- [x] Add release-please. **Nisha**
- [x] [Overview updates](https://github.com/NFDI4Chem/nmrxiv-docs/issues/154). **Chandu**
- [x] [Update File Format](https://github.com/NFDI4Chem/nmrxiv-docs/issues/118). **Noura**
- [x] [Update Ontologies](https://github.com/NFDI4Chem/nmrxiv-docs/issues/146). **Noura**
- [x] [Update Data Schema](https://github.com/NFDI4Chem/nmrxiv-docs/issues/147). **Noura**
- [x] [Update NMRium](https://github.com/NFDI4Chem/nmrxiv-docs/issues?q=is%3Aissue+is%3Aopen+NMRIUM). **Chandu Noura**
- [ ] [Update Development](https://docs.nmrxiv.org/docs/developer-guides/installation/development). **Nisha**
       [vite](https://github.com/NFDI4Chem/nmrxiv-docs/issues/143).
       [pint](https://github.com/NFDI4Chem/nmrxiv-docs/issues/144).
       [branching](https://github.com/NFDI4Chem/nmrxiv-docs/issues/95)
- [x] [Add Storage](https://github.com/NFDI4Chem/nmrxiv-docs/issues/121). **Nisha**
- [x] [Update CI/CD](https://github.com/NFDI4Chem/nmrxiv-docs/issues/76). **Nisha**
- [x] Update Environment. **Nisha**
- [x] [Update GKE](https://github.com/NFDI4Chem/nmrxiv-docs/issues/148). **Nisha**
- [x] [Update Helm](https://github.com/NFDI4Chem/nmrxiv-docs/issues/149). **Nisha**
- [x] [Update Architecture](https://github.com/NFDI4Chem/nmrxiv-docs/issues/48). **Chandu**
- [x] [Update Development Worflow](https://github.com/NFDI4Chem/nmrxiv-docs/issues/150). **Nisha**
- [x] [Update API](https://github.com/NFDI4Chem/nmrxiv-docs/issues/60). **Chandu Noura**
- [x] [Update Submission Guidelines](https://github.com/NFDI4Chem/nmrxiv-docs/issues/151). **Noura, Nisha & Chandu**
- [x] [Update Contribution](https://github.com/NFDI4Chem/nmrxiv-docs/issues/152). **Noura**
- [ ] [Update FAQs](https://github.com/NFDI4Chem/nmrxiv-docs/issues/153). **Chandu**
- [x] [Landing page update](https://github.com/NFDI4Chem/nmrxiv-docs/issues/137). **Nisha, Noura & Chandu**
- [x] [Content Restructing](https://github.com/NFDI4Chem/nmrxiv-docs/issues/117). **Nisha Noura & Chandu**

**Comment by NRayya** [comment]
https://github.com/NFDI4Chem/nmrxiv-docs/issues/145

**Comment by NishaSharma14** [comment]
Closing in favour of #891
