### ISSUE TITLE
NMRium issues

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#783]
- [x]  [Problem with determination of gyromagnetic ratio #1842 ](https://github.com/cheminfo/nmrium/issues/1842)
  - [x] Related to:  [2D FID crash jcampconverter #67 ](https://github.com/cheminfo/jcampconverter/issues/67)
- [x]  [Zipped 2D FID Bruker files not being recognized #2031  ](https://github.com/cheminfo/nmrium/issues/2031)
- [x]  [Enable reading peaks, ranges, multiplicity of jcamp files #2039 ](https://github.com/cheminfo/nmrium/issues/2039)
- [x]  [Hide FID spectrum when FT is available #2063 ](https://github.com/cheminfo/nmrium/issues/2063)
- [x]  [Programmatically configurable NMRium component views/panels #1521 ](https://github.com/cheminfo/nmrium/issues/1521)
- [x]  [Trigger callback on error / warning #1522 ](https://github.com/cheminfo/nmrium/issues/1522)
- [x]  [Ranges picking - Slows the browser and wrong multiplicity occasionally #2275](https://github.com/cheminfo/nmrium/issues/2275)
- [x] [ Checmical structures panel - Structures serialisation number not incremented after drawn strucutres #2303](https://github.com/cheminfo/nmrium/issues/2303)
- [x]  [Auto peaks picking - difficult to enter parameters numbers #2307](https://github.com/cheminfo/nmrium/issues/2307)
