### ISSUE TITLE
Project / Study colour selection and add to starred list feature

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#79]
**Description of the feature** 
As a user, I should be able to select a colour for my project and study. I should also be able to add my project/study to my starred lists. These should be accessed via quick link in the side bar.

**Implementation steps or Task**
- [x] Extend table schemas
- [x] Assign default values
- [x] Implement front end components
- [x] Persist data to the data base
